### ISSUE TITLE
Request Dataset

### ISSUE THREAD

**Issue by XiaoxiaoYang-com** [darwinquezada/SURIMI#1]
Hello, according to your prompt. The dataset I downloaded is incomplete, and some of the links inside cannot be accessed. Could you please share it with the teacher?

**Comment by darwinquezada** [comment]
Hello @Huihui2446,

I included some of the datasets in the folder "original_datasets". If you need any help running the experiments, please let me know!

**Comment by XiaoxiaoYang-com** [comment]
Thank you, teacher. The dataset is complete



---Original---
From: ***@***.***&gt;
Date: Wed, May 17, 2023 14:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [darwinquezada/SURIMI] Request Dataset (Issue #1)




 
Closed #1 as completed.
